### ISSUE TITLE
Versus Dynamic DNS?

### ISSUE THREAD

**Issue by davidstrauss** [syncthing/discosrv#1]
Is there a substantial difference between this and dynamic DNS (RFC 2136)? It looks like the code simply allows publishing a node ID to address(es) mapping, both for IPv4 and IPv6. It would be easier for people to run their own discovery server -- and for scaling the public ones -- if it didn't require maintaining custom software with its own API.

**Comment by briceburg** [comment]
+1 Great work thus far guys!

**Comment by generalmanager** [comment]
DNSSEC and even DANE are not really what we want:
http://sockpuppet.org/blog/2015/01/15/against-dnssec/
http://sockpuppet.org/stuff/dnssec-qa.html
https://www.imperialviolet.org/2015/01/17/notdane.html

FYI The first two posts are from Thomas Ptacek, a well known security professional and the third is from Adam Langley, Googles security guru, who also wrote the (probably) most secure anonymous communication tool that exists: Pond.

**Comment by davidstrauss** [comment]
Whatever reputation Ptacek may have, his post on DNSSec is incompetent.

It's not government-controlled PKI. It's controlled by the applicable TLD, only some of which are government-run. Additionally, certificate pinning provides zero access to private keys. At its worst potential abuse, a government could use it to cause broswers to show incorrect warnings.

It's not cryptographically weak because DNSSec isn't a specific algorithm any more than TLS is a specific encryption algorithm. Conflating the two shows lack of familiarity with the topic.

It's unclear why he thinks it's expensive to adopt or deploy, either, given that Google, Comcast, and other major vendors validate DNSSec data.

It's also not "incomplete," at least in any way that is substantially different from a browser using an OS-shipped set of CAs for TLS. Either you trust the OS or you don't. If you can't trust the OS to validate DNS lookups, then why would you trust it to ship trustable CAs?

The claim that DNSSec in unsafe relies purely on a "security through obscurity" hypothesis. It's quite important to prevent forgery of non-existent records, as it can redirect things like emails through forging higher-priority records than the correct ones. His only criticism against NSEC3 (including its solution to record disclosure) is that it's, apparently, complicated.

Also, DANE isn't at all what we've been talking about here, which is the only thing Langley is mentioning.

**Comment by generalmanager** [comment]
>DNSSec not government-controlled PKI. It's controlled by the applicable TLD, only some of which are government-controlled, and those are generally ones like ".us". In the FAQ, he acknowledges this but counters that "Google can't opt out of .com," which is a different argument -- and not one particular to DNSSec.

This kind of arguing is handwaving at best and malevolent at worst. If the root authorities of the trust system are sometimes adversaries, you can't simply put the average web user in charge of knowing the precise influence some governments may have on some domains. This kind of "experts will figure out how to do it securely" thinking is why we still don't have usable crypto, decades after the groundwork was laid.

This is so basic that it shouldn't need an example. But still. Take a look at the popularity statistics for TLDs:
http://w3techs.com/technologies/overview/top_level_domain/all

Wow, number three on this list with nearly 5% of all TLDs ever registered is .ru. Hmm wasn't there something a few years ago about this? Yes, in 2012 a government controlled blacklist was introduced with the charming name "Common register of domain names, Internet website page locators, and network addresses that allow identifying Internet websites which contain information that is prohibited for distribution in the Russian Federation."
You can read more about it here:
https://en.wikipedia.org/wiki/Internet_censorship_in_Russia

There have also been several documented attacks on the security of encrypted connections by countries like Turkey.

Regarding that Google can't opt out of .com: Of course this is relevant to DNSSEC. Not only to DNSSEC, but to every trust management system supposed to replace the incredibly broken X509 infrastructure. It means that the domain a website is registered under can not have an influence oo the trustworthiness of the connection. If the entity providing the trust isn't both trustworthy AND separate from the domain registrar, the system is broken.

>DANE-based certificate pinning provides no access to private keys. Ptacek wrongly implies that it does in the Bit.ly example. 

No, his bit.ly example only talks about DNSSEC. And DNSSEC doesn't solve the problem that state-owned or state-controlled registries have the power to subvert an encrypted connection, because they are the trust anchor.

>DANE-based certificate pinning provides no access to private keys. Ptacek wrongly implies that it does in the Bit.ly example. The worst potential abuse is a TLD owner publishing false public keys for domains and signing bad records. This abuse would cause browsers visiting those domains to possibly show certificate warnings or fail DNS lookups. If a TLD wants to take down a site, they would just mess with the nameserver records and be done; DNSSec doesn't offer them more power to compromise sites. What DNSSec does do it take the power to propagate bad DNS records away from everyone but the site owner and TLD.

Right, but if we are already going to replace a horribly broken system, we shouldn't replace it with a system, which is better in some aspects, but still doesn't really solve all the problems.

>DNSSec is also not cryptographically weak because DNSSec isn't any specific signing algorithm. The same concerns for signing algorithms apply to both TLS and DNSSec. Conflating DNSSec with its current algorithm options shows lack of familiarity with the system, at best. RSA is hardly broken, anyway. 

Yes, yes it is cryptographically weak. You are basically saying all the currently deployed implementations are weak and there is no big effort to improve this ASAP, but it can be improved, if we replace the bad signing algorithms with something stronger in the future.

With this kind of arguments TLS can be cryptographically stronger (not trustworthier) than this part DNSSEC, because some servers use strong ciphers, whereas strong signing algos aren't even part of the current DNSSEC set. 

>RSA is hardly broken, anyway.

1024 bit RSA can certainly be considered broken, since several state actors are believed to have the power to break them in acceptable time today. Which means that bigger companies or organized criminals will be able to do it in 5 years, while everbody else will be able to break it at home in 10 years. 

>Ptacek also says in the FAQ that the curves supported by DNSSec may be older but aren't actually broken.

And this is exactly what is generally beeing said before stuff breaks fantastically. Look at RC4. It was even used by many big services, even though it was known to be old and not state of the art, because it prohibited another attack. And then it imploded.

This follows your reasoning pattern to dismiss any criticism of algorithms as long as they are not completely broken just yet. Which simply doesn't reflect how security professionals work: regard everything that is not known to be good as possibly broken and avoid it.

>He portrays DNSSec as expensive to adopt or deploy by the trick of moving goalposts. He considers DNSSec "not deployed" until it's validated down to every OS or application, which ignores the power of validation Google, Comcast, and others perform. [...] My computer's security isn't just a product of the browser's validations.

What do you want to say about the power of validation? The typical domain-validation certificates are a joke. And any system that doesn't siginficantly improve in this regard is broken.

The argument that it is difficult to deploy certainly holds some truth. Most registrars don't even offer it, many charge a markup and the fact that you found two which do it for free doesn't mean that it's commonly easily and cheaply deployed. It's like saying that TLS certificates are free, because there are one or two CAs which hand out free certificates.

>DNSSec is also not "incomplete," at least in any way that is substantially different from a browser using an OS-shipped set of certificate authorities (CAs). If you can't trust the OS to validate DNS lookups, then you can't trust it to ship good CAs. Obviously, cases like Lenovo's recent flap show that it's not always a good idea to trust the OS, but that's not a DNSSec-specific issue. 

DNSSEC is supposed to be used as a protocol on the lowest levels, but still doesn't provide the assurances needed from a system that is supposed to replace what we have now.

That's not as user-replaceable as the OS.

From Ptaceks post:
>Even if DNSSEC was deployed universally and every zone on the Internet was signed, a coffee-shop attacker would still be able to use DNS to man-in-the-middle browsers.

From your post:
>Nothing stops applications from performing their own DNS lookups anyway; it's actually very common.

And now endusers are supposed to check if the programs they care about do this? Please...


>Ptacek claim that DNSSec is unsafe relies on a "security through obscurity" approach of hiding host information. It's actually more important to prevent forgery of non-existent records because forged, high priority MX records can redirect things like emails to malicious targets. Of course, DNSSec has actually solved the disclosure issue with NSEC3, which he mentions. His only criticism against NSEC3 is that it's, apparently, complicated.

No it isn't. It's that the default is insecure and that the supposed workaround is a joke where some fake entries are made to make cracking harder.
And not publicly devulging the addresses under which testing, staging and production servers can be reached is not security trough obscurity. Just like changing the SSH port to something else isn't. At the very least it significantly reduces the noise in the log files, by filtering out standard port scans by script kiddies. At best less competent attackers won't even start a targeted attack, because they don't know where to begin. Oh and btw: the more complicated a system is, the higher the likelyhood of vulnerabilities.

In his words:
>In the past couple years (reminder: DNSSEC has been “ready to deploy” for almost 15 years), the DNSSEC standards project has solved this problem, if we accept as a “solution” “NSEC3 and “minimum covering NSEC records” with online signers managing DNS zones as a sort of bizarro Unix password file in which fake records are added at random to foil password crackers Confused? Don’t worry, there’s an NSEC5 coming too. . This mode of deployment is, of course, not the default.

>For everyone who accepts the default, every hostname in their DNS zones are public information. This works for the kind of person who works on standardizing DNS extensions, because their hostnames are things like “dec-multia-in-my-basement.greybeard.com”. It does not work so well for Bank of America.

And as everybody with experience in security knows: if the defaults aren't good, there will be many spectacular incidences of the system failing.

>Finally (and most importantly), DANE isn't actually what we've been talking about here, which is the only thing Langley mentions. Langley is also more charitable than I am with Ptacek's piece; he merely says, "We don't fully agree on everything." I think Langley's piece is quite good, though his annoyance with 1024-bit RSA is not well founded as long as DNSSec serves as additional verification/forgery difficulty, not the single source of truth.

And again: that something isn't entirely broken and utterly useless just yet is certainly no reason to use it.

>What I was proposing was regular host records (A and AAAA) for the sake of discovering peers by fingerprint or other name. Obviously, you want the data to be trustworthy and the service to scalable. DNSSec may not be the best answer for that in SyncThing's case, but arguments for and against should be based in good data, not rants.

Apart from that we disagree on the rant part, I don't think requiring DNSSEC from everybody who wants to run a discovery server is going to do the state of decentralization any good.
The more difficult it is to setup (and DNSSEC is a BIG dependency), the less people will be able to run their own.

To quote @AudriusButkevicius:
>Why do we need to verify the authenticity of the relay, if the messages the relay is relaying are themselves verifiable and not temperable with?

**Comment by davidstrauss** [comment]
> This kind of arguing is handwaving at best and malevolent at worst. If the root authorities of the trust system are sometimes adversaries, you can't simply put the average web user in charge of knowing the precise influence some governments may have on some domains. This kind of "experts will figure out how to do it securely" thinking is why we still don't have usable crypto, decades after the groundwork was laid.

With CAs, every authority is a potential adversary. Some authorities are government-controlled, making all certificates vulnerable to them. With DNSSec, you have one potential adversary: the authority over the TLD's keys. That may be a government, but at least it's only one.

> Wow, number three on this list with nearly 5% of all TLDs ever registered is .ru.

It shouldn't be a surprise that registering a domain under .ru puts the domain at the discretion of the Russian government. Whether that discretion only includes nameservers or also includes DNSSec, they can choose to take down sites from their TLD that they don't like.

> Not only to DNSSEC, but to every trust management system supposed to replace the incredibly broken X509 infrastructure.

DNSSec does not intend to replace x.509 in any part. Even with DANE certificate pinning, it's just an additional (and optional) source of trust that makes a CA compromise less of a disaster.

> No, his bit.ly example only talks about DNSSEC.

He said, "Had DNSSEC been deployed 5 years ago, Muammar Gaddafi would have controlled BIT.LY’s TLS keys." That's completely false. Every browser validates the x.509 chain to a CA, regardless of using DANE. At most, a browser will also check the fingerprint against a DANE record as a second trust anchor. If someone forges malicious DANE records, that will not cause browsers to trust that fingerprint (or the corresponding certificate). It would cause browsers implementing DANE to question or disallow use of the proper certificate, which would be denial of service at most.

It would have been impossible to "control Bit.ly's TLS keys" using DNSSec.

> And DNSSEC doesn't solve the problem that state-owned or state-controlled registries have the power to subvert an encrypted connection, because they are the trust anchor.

As I said before, it's an additional trust anchor, not a replacement one. Compromising a single trust anchor (of two, the second being the CA) does not allow subverting an encrypted connection. Denial-of-service isn't subversion of encryption.

> 1024 bit RSA can certainly be considered broken, since several state actors are believed to have the power to break them in acceptable time today. Which means that bigger companies or organized criminals will be able to do it in 5 years, while everbody else will be able to break it at home in 10 years.

"Broken" is a technical term in cryptography; it means that a finding the key for a given piece of encrypted data has become considerably faster than brute-force, even in limited situations (weak keys or known/supplied text). RSA is not broken in this sense. The ability to brute-force 1024-bit keys simply means longer keys are necessary. DNSSec supports 2048-bit RSA and longer, and people should use those if they want to use RSA. This is no more a problem for DNSSec than TLS or other systems where algorithms are selectable.

> And this is exactly what is generally beeing said before stuff breaks fantastically. Look at RC4. It was even used by many big services, even though it was known to be old and not state of the art, because it prohibited another attack. And then it imploded.

Comparing current NIST elliptic curve algorithms to RC4 is unfair. RC4 has been known broken for over a decade, and was suspected to be for far longer. There are no known issues with the EC algorithms in DNSSec, even suspected.

> This follows your reasoning pattern to dismiss any criticism of algorithms as long as they are not completely broken just yet.

No, my reasoning that DNSSec offers secure algorithms is based on prevailing opinions in the cryptography community -- and understanding that anything DNSSec provides is additional security versus no signing at all. That means "broken" DNSSec results in falling back to nothing at all (or, at worst, denial of service).

> What do you want to say about the power of validation? The typical domain-validation certificates are a joke. And any system that doesn't siginficantly improve in this regard is broken.

DNSSec keys have to be loaded into a registrar, so at least there's not the ability to achieve "domain validation" through DNS, email, or putting a file onto an HTTP server. All of those "domain validation" methods are also subject to compromise without DNSSec or existing TLS, the latter of which creates a chicken/egg situation for obtaining the first domain-validated certificate. So, yes, I'd say it is better than the way we do domain validation right now -- and also allows domain validation to be more secure.

> The argument that it is difficult to deploy certainly holds some truth. Most registrars don't even offer it, many charge a markup and the fact that you found two which do it for free doesn't mean that it's commonly easily and cheaply deployed. It's like saying that TLS certificates are free, because there are one or two CAs which hand out free certificates.

The CAs that hand out free certificates (like CAcert) aren't trusted widely by browsers, making them unusable for most purposes. In contrast, registrars that provide free DNSSec key publishing are equal to any other registrar that does so. Moreover, some of the largest registrars, like GoDaddy and Gandi, provide free DNSSec. It's possible to deploy DNSSec completely for free in a trusted way, so there's really no comparison.

In any case, DNSSec doesn't compete with x.509, so DNSSec isn't a solution to problems with certificate costs.

> DNSSEC is supposed to be used as a protocol on the lowest levels, but still doesn't provide the assurances needed from a system that is supposed to replace what we have now.

There's no "supposed to be" other than "as many places as possible." It should be like bouncers checking for fake IDs: when they find one, they take it and throw it out, preventing further use of the ID under less critical eyes. And, again, it's not supposed to replace anything we have now.

> And now endusers are supposed to check if the programs they care about do this? Please...

Just as it's the responsibility of browsers to make end-users aware of whether an HTTPS connection is secure, browsers can do the same for any lookups they may do (or using other trust mechanisms, like DANE). DNSSec doesn't have a better answer for surfacing security data to the user, but I don't think it's any worse.

> It's that the default is insecure and that the supposed workaround is a joke where some fake entries are made to make cracking harder.

It makes it harder in the sense that cracking long-key RSA is hard. The "fake" records are, essentially, the established distributed systems concept of using tombstones to indicate deleted records. It's a signed tombstone that establishes the "deletion" of any record that should not exist so that one cannot be forged (and old but originally legitimate records get flushed).

> Oh and btw: the more complicated a system is, the higher the likelyhood of vulnerabilities.

You're raising these concerns about vulnerabilities without asking the critical question of "What happens if that breaks? How bad is it?" If NSEC3 breaks, then you could get addresses and pinned public keys, which should not compromise anything directly. NSEC3 is defense-in-depth, just as unlisted hosts on any DNS server should be defense-in-depth.

> And as everybody with experience in security knows: if the defaults aren't good, there will be many spectacular incidences of the system failing.

I'm not really clear on what Ptacek means by "not the default." NSEC3 is one among the two methods for publishing the tombstone records. As far as I can tell, it's neither the default nor not the default. Maybe Ptacek thinks it's "not the default" because it's slightly newer than the record-revealing method, but NSEC3 is still mandatory. Any functional default comes from what DNS servers and services choose as their defaults.

> And again: that something isn't entirely broken and utterly useless just yet is certainly no reason to use it.

I agree that DNSSec offers older algorithm options (in addition to the newer options) that, if used, are less secure. I agree that applications and operating systems don't validate DNSSec nearly as much that ought to for DNSSec to be maximally effective. But I'm still unclear to me why Ptacek or you think DNSSec is broken in any true sense, especially in its intended role as an addition to a "defense in depth" arsenal.

I think a large degree of the argument is what DNSSec is intended to do. I see it like the US Treasury adding an additional, hard-to-forge security feature to paper currency: not perfect or always checked but a useful addition to forgeries.

> Apart from that we disagree on the rant part, I don't think requiring DNSSEC from everybody who wants to run a discovery server is going to do the state of decentralization any good.
The more difficult it is to setup (and DNSSEC is a BIG dependency), the less people will be able to run their own.

That's reasonable.

**Comment by AudriusButkevicius** [comment]
I think this is no longer relevant?
Yeah DDNS is nice, but it's easier to set up an announce server than a DNS server which supports DNSSEC.
