### ISSUE TITLE
In a dual stack  IPv4/IPv6 environment may fail

### ISSUE THREAD

**Issue by iggs0** [syncthing/discosrv#35]
I have a dual stack subnet with IPv6/v4 and a WLAN Subnet which has only IPv4 connectivity. (The WLAN router does not support v6 propperly :-( )

I faced the issue that the machines in the IPv4 WLAN cloud not interact with the dual stack network syncthing nodes. I run a discosrv to allow this. 
I finally found out, that the reply to the IPv4 only machine for looking up a syncthing node on the dual stack subnet was only a IPv6 address.
This obviously does not work. Forcing discosrv to listen only to IPv4 solved the problem - but it would be better to have the syncthing nodes report with all addresses to the discosrv and the discosrv on the other hand should return the needed value (called by IPv4 -> return IPv4 ....)

**Comment by calmh** [comment]
We do report all addresses, but the announcing device only announces once to each discovery server. In a dual stack setup, that connection will probably prefer IPv6 so that's all the discovery server knows about. 

The official discovery servers are all IPv4-only or IPv6-only (run as two instances on the same hardware).

**Comment by iggs0** [comment]
As usual - thank you very much for you extremely fast replies.
I agree with you analysis and that it is very difficult to fix - since it is not a application problem.
Maybe it would help to document this somewhere.
=> Issue closed
